### ISSUE TITLE
How to install SecureDNS, there is currently no detailed tutorial

### ISSUE THREAD

**Issue by thb007** [Texnomic/SecureDNS#1]
I want to install on Debian9 system, but I can't find the installation tutorial.

**Comment by Texnomic** [comment]
SecureDNS doesn't require installation, just simply download the **Linux-x64 Portable Binary** and execute it directly.

**Comment by thb007** [comment]
> SecureDNS不需要安装，只需下载**Linux-x64 Portable Binary**并直接执行即可。

Do you support Raspberry Pi 3b + and 4b?

**Comment by Texnomic** [comment]
Yes, download **Linux-ARM64 Portable Binary**. Also you can check wiki pages for [Supported-Processor-Architecture](https://github.com/Texnomic/SecureDNS/wiki/Supported-Processor-Architecture) & [Supported-Operating-Systems](https://github.com/Texnomic/SecureDNS/wiki/Supported-Operating-Systems).
