### ISSUE TITLE
Linux-Arm64 package is not for Arm64

### ISSUE THREAD

**Issue by jedisct1** [Texnomic/SecureDNS#2]
Hi!

It looks like the `Linux-Arm64` package is for 32-bit ARM, not ARM64:

```sh
$ file Texnomic.SecureDNS.Terminal
Texnomic.SecureDNS.Terminal: ELF 32-bit LSB executable, ARM
```

So, unfortunately, it doesn't run on Linux/aarch64.

**Comment by Texnomic** [comment]
Hi, 

Sorry it was my mistake while publishing, I've re-compiled & [re-uploaded](https://github.com/Texnomic/SecureDNS/releases/download/v0.3-alpha/Linux-Arm64.7z) it:

`Texnomic.SecureDNS.Terminal: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=c48187bb9d9d9086aeb4828095c1777459e5565b, stripped` 

Finally, thank you for reporting this issue as i've discovered that the release is missing Win-Arm64, Linux-musl-x64 & Linux-Arm 👍
