### ISSUE TITLE
error when running the program

### ISSUE THREAD

**Issue by Causty** [Texnomic/SecureDNS#53]
![Snap 2020-08-15 at 22 16 10](https://user-images.githubusercontent.com/34654249/90313135-12d66780-df45-11ea-9583-b6dc138ead9c.png)

**Comment by Causty** [comment]
i forgot that i have simple dnscrypt running in the background and i didn't turn off its service. after i turn off simple dnscrypt, secure dns start as intended

**Comment by Texnomic** [comment]
Also take note that I you have Docker Installed, it will lock port 53 also with Internet Sharing Service.
