### ISSUE TITLE
PURE NetCore

### ISSUE THREAD

**Issue by AZ-X** [Texnomic/SecureDNS#92]
I forked the project on May 6, since it could be a good project for .Core things.
Found two commits related and was only in a day interval after my pulling.
https://github.com/Texnomic/SecureDNS/commit/2e6bdfcc9b49a783cf48d86b08da6418f4f2e939
https://github.com/Texnomic/SecureDNS/commit/1659a0b4ebafecf947b69835f635916ed23331fe
It looks weird.
Now I think it's a good idea to evaluate this library: https://github.com/TimothyMeadows/AeadChaCha20Poly1305.NetCore
which refers to https://github.com/TimothyMeadows/ChaCha20.NetCore and https://github.com/TimothyMeadows/Poly1305.NetCore
A scrupulous banker knows the difference from NSec and has ambition to make this project great again.
Please find my codes in Go-lang related: https://github.com/AZ-X/dnscrypt-proxy-r2/blob/master/dnscrypt-proxy/unclassified/xsecretbox.go

**Comment by Texnomic** [comment]
Well, good question, in order to support DNSCrypt, we needed libsodium with a wrapper for .NET Core, we tested many nugets but non was having complete implementation so we decided to build our own which exposes all of the needed functions for DNSCrypt to work with full feature coverage,

**Comment by AZ-X** [comment]
@Texnomic I would rather see the implementation base on 'PURE NetCore' than some wrapper of oddments.
Take a look: https://github.com/dchest/tweetnacl-js/blob/master/nacl.js
The total line of code in JavaScript is less than [Refactoring Texnomic.Chaos.NaCl Project.](https://github.com/Texnomic/SecureDNS/commit/2e6bdfcc9b49a783cf48d86b08da6418f4f2e939)
Hopefully you and your team could find a right way to achieve the coverage.
