### ISSUE TITLE
Dns over tls isnt resolving anything else than google developers

### ISSUE THREAD

**Issue by JunaidShafi** [Texnomic/SecureDNS#99]
On setting mode to tls nothing works only google developers site gets resolved

**Comment by Texnomic** [comment]
Please share the Error Log (Console Window or Seq Logs) to be able to support you.

**Comment by JunaidShafi** [comment]
[log.txt](https://github.com/Texnomic/SecureDNS/files/5819410/log.txt)

**Comment by JunaidShafi** [comment]
Please look into this

**Comment by Texnomic** [comment]
You need to add IP & Domain of TLS DNS Server in `HostTable` Section in `AppSetting.json` File.

**Comment by JunaidShafi** [comment]
thats already there

**Comment by JunaidShafi** [comment]
[AppSettings - Copy.txt](https://github.com/Texnomic/SecureDNS/files/5819744/AppSettings.-.Copy.txt)
